# Pandas + PostgreSQL

Exemplo simples mostrando como trazer dados do **PostgreSQL diretamente para um DataFrame Pandas** usando `pd.read_sql()`.

### Fluxo

`PostgreSQL → Pandas DataFrame`

## 1. Bibliotecas

Vamos utilizar:

- **Pandas** → trabalhar com os dados em `DataFrame`
- **SQLAlchemy** → criar a conexão utilizada pelo Pandas para acessar o PostgreSQL

Se necessário:

```bash
pip install pandas sqlalchemy psycopg2-binary
```

In [23]:
import pandas as pd
from sqlalchemy import create_engine, text

## 2. Conexão com PostgreSQL

Criamos um **Engine** do SQLAlchemy.

O objetivo aqui não é estudar SQLAlchemy ORM. Ele está sendo usado apenas como a conexão que o Pandas utilizará para acessar o PostgreSQL.

> ⚠️ Substitua os dados pelos dados do seu ambiente.

In [26]:
engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/loja_brasil"
)

print("Conexão configurada!")

Conexão configurada!

## 3. `pd.read_sql()`

Agora podemos escrever uma consulta SQL e passar o `engine` para o Pandas.

O resultado já será um **DataFrame**.

Sem precisar fazer manualmente `cursor()`, `execute()`, `fetchall()` e `pd.DataFrame()`.

In [15]:
df_clientes = pd.read_sql(
    "SELECT * FROM cadastro.clientes;",
    engine
)

df_clientes

,id_cliente,nome,email,cidade,estado,data_cadastro,ativo
0,2,Bruno Henrique Souza,bruno.souza@email.com,Pomerode,SC,2025-01-16,True
1,3,Camila Rodrigues,camila.rodrigues@email.com,Joinville,SC,2025-01-27,True
2,4,Daniel Oliveira,daniel.oliveira@email.com,Itajaí,SC,2025-02-07,True
3,5,Eduarda Fernandes,eduarda.fernandes@email.com,Florianópolis,SC,2025-02-18,True
4,6,Felipe Almeida,felipe.almeida@email.com,Brusque,SC,2025-03-01,True
5,7,Gabriela Costa,gabriela.costa@email.com,Blumenau,SC,2025-03-12,True
6,8,Henrique Martins,henrique.martins@email.com,Jaraguá do Sul,SC,2025-03-23,True
7,9,Isabela Santos,isabela.santos@email.com,Rio do Sul,SC,2025-04-03,True
8,10,João Pedro Lima,joao.lima@email.com,Timbó,SC,2025-04-14,True
9,11,Karina Souza,karina.souza@email.com,Gaspar,SC,2025-04-25,True
10,12,Lucas Pereira,lucas.pereira@email.com,Indaial,SC,2025-05-06,True
11,13,Mariana Alves,mariana.alves@email.com,Blumenau,SC,2025-05-17,True
12,14,Natália Rocha,natalia.rocha@email.com,São José,SC,2025-05-28,True
13,15,Otávio Ribeiro,otavio.ribeiro@email.com,Chapecó,SC,2025-06-08,True
14,16,Patrícia Mendes,patricia.mendes@email.com,Blumenau,SC,2025-06-19,True
15,17,Rafael Gomes,rafael.gomes@email.com,Pomerode,SC,2025-06-30,True
16,18,Sabrina Teixeira,sabrina.teixeira@email.com,Itajaí,SC,2025-07-11,True
17,19,Thiago Nunes,thiago.nunes@email.com,Balneário Camboriú,SC,2025-07-22,True
18,20,Vanessa Cardoso,vanessa.cardoso@email.com,Brusque,SC,2025-08-02,True
19,1,Ana Paula Martins,ana.martins@email.com,Florianópolis,SC,2025-01-05,True
20,25,Ana Maria,ana.maria@email.com,Blumenau,SC,2026-09-09,True
21,26,Ana Souza,ana.souza@email.com,Pomerode,SC,2026-09-09,True
22,27,Carlos Lima,carlos.lima@email.com,Joinville,SC,2026-09-09,True

## 4. SELECT com filtro

Podemos continuar utilizando SQL normalmente.

In [4]:
df_blumenau = pd.read_sql(
    """
    SELECT id_cliente, nome, cidade, email
    FROM cadastro.clientes
    WHERE cidade = 'Blumenau';
    """,
    engine
)

df_blumenau

   id_cliente             nome    cidade                      email
0           7   Gabriela Costa  Blumenau   gabriela.costa@email.com
1          13    Mariana Alves  Blumenau    mariana.alves@email.com
2          16  Patrícia Mendes  Blumenau  patricia.mendes@email.com
3          25        Ana Maria  Blumenau        ana.maria@email.com

## 5. SELECT + JOIN

Também podemos executar consultas com `JOIN` e receber o resultado diretamente como DataFrame.

In [6]:
df_pedidos = pd.read_sql(
    """
    SELECT
        c.nome,
        p.id_pedido,
        p.data_pedido
    FROM cadastro.clientes AS c
    INNER JOIN vendas.pedidos AS p
        ON p.id_cliente = c.id_cliente;
    """,
    engine
)

df_pedidos.head()

                   nome  id_pedido data_pedido
0      Henrique Martins          1  2025-02-10
1        Otávio Ribeiro          2  2025-02-19
2  Bruno Henrique Souza          3  2025-02-28
3        Isabela Santos          4  2025-03-09
4       Patrícia Mendes          5  2025-03-18

## 6. SELECT + GROUP BY

Podemos utilizar funções de agregação no SQL e receber o resultado no Pandas.

In [7]:
df_resumo = pd.read_sql(
    """
    SELECT
        cidade,
        COUNT(*) AS quantidade_clientes
    FROM cadastro.clientes
    GROUP BY cidade
    ORDER BY quantidade_clientes DESC;
    """,
    engine
)

df_resumo

                cidade  quantidade_clientes
0             Blumenau                    4
1             Pomerode                    3
2        Florianópolis                    2
3               Itajaí                    2
4              Brusque                    2
5            Joinville                    2
6                Timbó                    1
7             São José                    1
8       Jaraguá do Sul                    1
9              Chapecó                    1
10             Indaial                    1
11              Gaspar                    1
12  Balneário Camboriú                    1
13          Rio do Sul                    1

## 7. Depois disso, usamos Pandas

Depois que os dados estão no DataFrame, podemos utilizar normalmente os recursos do Pandas.

In [8]:
df_resumo.sort_values(
    "quantidade_clientes",
    ascending=False
)

                cidade  quantidade_clientes
0             Blumenau                    4
1             Pomerode                    3
2        Florianópolis                    2
3               Itajaí                    2
4              Brusque                    2
5            Joinville                    2
6                Timbó                    1
7             São José                    1
8       Jaraguá do Sul                    1
9              Chapecó                    1
10             Indaial                    1
11              Gaspar                    1
12  Balneário Camboriú                    1
13          Rio do Sul                    1

## 8. Resumo

### Com Psycopg2

```text
SQL
 ↓
cursor.execute()
 ↓
fetchall()
 ↓
pd.DataFrame()
```

### Com `pd.read_sql()`

```text
SQL
 ↓
pd.read_sql()
 ↓
DataFrame
```

> **`pd.read_sql()` simplifica o processo de trazer dados do PostgreSQL para o Pandas.**

O SQL continua sendo escrito normalmente; a diferença é que o resultado já chega como um **DataFrame**.

### 9. Inserindo registros no PostgreSQL

In [17]:
# Criando novos clientes para inserir no banco de dados
df_novos_clientes = pd.DataFrame({
    "nome": ["João da Silva"],
    "Cidade": ["Criciúma"],
    "estado": ["SC"],
    "email": ["joao.silva@email.com"]
})

In [10]:
df_novos_clientes

            nome    Cidade estado                 email
0  João da Silva  Criciúma     SC  joao.silva@email.com

In [14]:
df_novos_clientes.to_sql(
    "Clientes", # nome da tabela que receberá os dados
    con=engine, # conexão com o banco de dados
    schema="cadastro", # schema onde a tabela está localizada
    if_exists="append", # se a tabela já existir, os dados serão adicionados no final
    index=False # não incluir o índice do DataFrame como coluna na tabela
    
)

print("Registro adicionado com sucesso!")

Registro adicionado com sucesso!

In [20]:
df_teste = pd.read_sql(
    """
    SELECT *
    FROM cadastro.clientes
    order by id_cliente DESC
    limit 5;
    """, con=engine
)

df_teste

,id_cliente,nome,email,cidade,estado,data_cadastro,ativo
0,27,Carlos Lima,carlos.lima@email.com,Joinville,SC,2026-09-09,True
1,26,Ana Souza,ana.souza@email.com,Pomerode,SC,2026-09-09,True
2,25,Ana Maria,ana.maria@email.com,Blumenau,SC,2026-09-09,True
3,20,Vanessa Cardoso,vanessa.cardoso@email.com,Brusque,SC,2025-08-02,True
4,19,Thiago Nunes,thiago.nunes@email.com,Balneário Camboriú,SC,2025-07-22,True

In [18]:
df_clientes.tail()

,id_cliente,nome,email,cidade,estado,data_cadastro,ativo
18,20,Vanessa Cardoso,vanessa.cardoso@email.com,Brusque,SC,2025-08-02,True
19,1,Ana Paula Martins,ana.martins@email.com,Florianópolis,SC,2025-01-05,True
20,25,Ana Maria,ana.maria@email.com,Blumenau,SC,2026-09-09,True
21,26,Ana Souza,ana.souza@email.com,Pomerode,SC,2026-09-09,True
22,27,Carlos Lima,carlos.lima@email.com,Joinville,SC,2026-09-09,True

In [21]:
df_teste

,id_cliente,nome,email,cidade,estado,data_cadastro,ativo
0,27,Carlos Lima,carlos.lima@email.com,Joinville,SC,2026-09-09,True
1,26,Ana Souza,ana.souza@email.com,Pomerode,SC,2026-09-09,True
2,25,Ana Maria,ana.maria@email.com,Blumenau,SC,2026-09-09,True
3,20,Vanessa Cardoso,vanessa.cardoso@email.com,Brusque,SC,2025-08-02,True
4,19,Thiago Nunes,thiago.nunes@email.com,Balneário Camboriú,SC,2025-07-22,True

In [29]:
with engine.begin() as conn:
    conn.execute(
        text(
        """
        update cadastro.clientes
        set cidade = :cidade
        WHERE id_cliente = :id_cliente;
        """
    ),
    {
        "cidade": "Bombinhas",
        "email": "joao.silva@example.com"

    }
    )

StatementError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'id_cliente'
[SQL:
        update cadastro.clientes
        set cidade = %(cidade)s
        WHERE id_cliente = %(id_cliente)s;
        ]
[parameters: [{'cidade': 'Bombinhas', 'email': 'joao.silva@example.com'}]]
(Background on this error at: https://sqlalche.me/e/20/cd3x)